### ISSUE TITLE
The download link for the ‘mpi3d_toy’ dataset appears to be broken or inactive

### ISSUE THREAD

**Issue by payphonePYF** [thomassutter/mvhg#1]
Could you share the file located at https://storage.googleapis.com/disentanglement_dataset/data_npz/sim_toy_64x_ordered_without_heldout_factors.npz
Thank you very much！

**Comment by thomassutter** [comment]
Hi, we are not the owners of the mentioned dataset. Unfortunately, the link on their github is not working anymore.
Please contact the owners of the original  [mpi3d dataset](https://github.com/rr-learning/disentanglement_dataset).
